ORG手册
* 1.介绍 
** 1.1 简介
   org模式是一种快速、高效的纯文本标记语言，用来保存笔记，记录TODO列表和
项目计划。它也是一种对文字编辑和可重复研究有特别支持的创作系统。
   大纲模式(outline mode)也会在顶层调用org模式，使其能够更好的架构大文件
的内容。可视化循环折叠和结构编辑使工作更加有条理。内置的表格编辑器使创建表格
更加容易。纯文本类URL链接可以把网站、电子邮件、usenet messages、BBDB entries
及任何项目相关的文件连接起来。
   org围绕包含有关项目列表或信息的纯文本笔记文件发展出了结构化的任务管理。
项目计划和任务管理使用了作为大纲节点的元数据。基于这个数据，在查询和创建动态日程
查看(同时集成了Emacs的日历和日记)时，它可以提取出特定的入口。org能够实现许多
不同项目的计划组合，例如David Allen`s GTD system。
   org可以通过输出不同格式的文件，如HTML、LATEX、Open Document和Markdown
充当某一创作系统。新的后端可以从已有的或从scratch定义的导出。
   org文件通过源代码块功能，使其非常适合用于包含代码示例的技术文档写作。org源
代码块十分的有用，可以在适当的位置对它们进行评估，它们的结果可以在文件内获取。
这使得创建单文件可重复研究纲要成为可能。
   org保留了简单特性。初次使用，它就想一个简单明了的大纲视图。没有强制的复杂
功能，但是当你需要时，也有许多功能可以调用。org是一个工具盒。实际上，许多用户
只使用了org的一小部分功能，他们知道还有更多的功能可以在任何需要的时候使用。
   所有的这些由纯粹的纯文本文件实现，这个文件格式更轻便且不过时。org运行于
Emacs中。Emacs是可广泛移植的程序，所以org也几乎可在任何主流平台上运行。
   org的网站提供了最新版本的org，及一些额外的信息，常见问题，教程等等。
请访问https://orgmode.org
   最新版本（7.3）的平装纸质手册已经由Network Theory Ltd发行。
** TODO 1.2 安装
   org包含在了最新的GNU Emacs版本中，所以你可能并不需要去安装它。大多数用户
可以简单的激活org模式并探索其功能。
   如果，因某些原因，你需要去安装org的最新版本。你可以使用一下三种方法：
1.使用Emacs的包管理系统；
2.以文档的形式下载org；
3.通过org的git仓库。
我们强烈建议只使用其中的一种方式。

使用Emacs的包管理系统

** 1.3激活
   org模式缓冲区需要打开字体锁定，Emacs中是默认打开的。如果你不想全局打开字体
锁定功能，那么就单独在org模式中打开，把以下代码加入达到你的配置中
(add-hook 'org-mode-hook 'turn-on-font-lock)
   在org模式和一些Elisp包之间会存在一些兼容问题，具体请查看（15.12.2冲突）。
请花一些时间查看列表。
   为了有更好的体验，这里有三个org命令应当绑定到Emacs的全局快捷键中，而不仅仅
是org缓冲区，它们分别是org-store-link,org-capture,org-agenda。Emacs中
有一些快捷键是为用户保留的。以下是一些建议，你也可以根据自己的喜好去绑定。
(global-set-key (kbd "C-c l") 'org-store-link
(global-set-key (kbd "C-c a") 'org-agenda)
(global-set-key (kbd "C-c c") 'org-capture)
以.org为扩展名的文件默认使用org模式打开。
