ORG手册
* 1.介绍 
** 1.1 简介
   org模式是一种快速、高效的纯文本标记语言，用来保存笔记，记录TODO列表和
项目计划。它也是一种对文字编辑和可重复研究有特别支持的创作系统。
   大纲模式(outline mode)也会在顶层调用org模式，使其能够更好的架构大文件
的内容。可视化循环折叠和结构编辑使工作更加有条理。内置的表格编辑器使创建表格
更加容易。纯文本类URL链接可以把网站、电子邮件、usenet messages、BBDB entries
及任何项目相关的文件连接起来。
   org围绕包含有关项目列表或信息的纯文本笔记文件发展出了结构化的任务管理。
项目计划和任务管理使用了作为大纲节点的元数据。基于这个数据，在查询和创建动态日程
查看(同时集成了Emacs的日历和日记)时，它可以提取出特定的入口。org能够实现许多
不同项目的计划组合，例如David Allen`s GTD system。
   org可以通过输出不同格式的文件，如HTML、LATEX、Open Document和Markdown
充当某一创作系统。新的后端可以从已有的或从scratch定义的导出。
   org文件通过源代码块功能，使其非常适合用于包含代码示例的技术文档写作。org源
代码块十分的有用，可以在适当的位置对它们进行评估，它们的结果可以在文件内获取。
这使得创建单文件可重复研究纲要成为可能。
   org保留了简单特性。初次使用，它就想一个简单明了的大纲视图。没有强制的复杂
功能，但是当你需要时，也有许多功能可以调用。org是一个工具盒。实际上，许多用户
只使用了org的一小部分功能，他们知道还有更多的功能可以在任何需要的时候使用。
   所有的这些由纯粹的纯文本文件实现，这个文件格式更轻便且不过时。org运行于
Emacs中。Emacs是可广泛移植的程序，所以org也几乎可在任何主流平台上运行。
   org的网站提供了最新版本的org，及一些额外的信息，常见问题，教程等等。
请访问https://orgmode.org
   最新版本（7.3）的平装纸质手册已经由Network Theory Ltd发行。
** TODO 1.2 安装
   org包含在了最新的GNU Emacs版本中，所以你可能并不需要去安装它。大多数用户
可以简单的激活org模式并探索其功能。
   如果，因某些原因，你需要去安装org的最新版本。你可以使用一下三种方法：
1.使用Emacs的包管理系统；
2.以文档的形式下载org；
3.通过org的git仓库。
我们强烈建议只使用其中的一种方式。

使用Emacs的包管理系统

** 1.3激活
   org模式缓冲区需要打开字体锁定，Emacs中是默认打开的。如果你不想全局打开字体
锁定功能，那么就单独在org模式中打开，把以下代码加入达到你的配置中
(add-hook 'org-mode-hook 'turn-on-font-lock)
   在org模式和一些Elisp包之间会存在一些兼容问题，具体请查看（15.12.2冲突）。
请花一些时间查看列表。
   为了有更好的体验，这里有三个org命令应当绑定到Emacs的全局快捷键中，而不仅仅
是org缓冲区，它们分别是org-store-link,org-capture,org-agenda。Emacs中
有一些快捷键是为用户保留的。以下是一些建议，你也可以根据自己的喜好去绑定。
(global-set-key (kbd "C-c l") 'org-store-link
(global-set-key (kbd "C-c a") 'org-agenda)
(global-set-key (kbd "C-c c") 'org-capture)
以.org为扩展名的文件默认使用org模式打开。如果想打开一个后缀名不是org的文件，可以
在文件首行加入以下字符：
    MY PROJECTS    -*- mode: org; -*-
这些字符使得当前编辑区打开org模式而不论文件后缀名是什么。也可以参考变量
org-insert-mode-line-in-empty-file.
   当前区域激活的情况下，许多org命令是可以使用的。为了确保命令可用，你需要打开
transient-mark-mode，默认情况下是打开的。如果你不喜欢transient-mark-mode,
你可以通过用鼠标选择的方式新建一个活动区域，或者在移动光标钱按两次C-SPC。
** TODO 1.4反馈
   如果你在使用org过程中发现问题，或者你有问题、建议、点子等，请发邮件给我们，
邮箱是emacs-orgmode@gnu.org。
** TODO 1.5本手册的字体显示惯例

* 文本结构
   org是一个大纲形式的文本。大纲允许一个文件按等级结构来组织，这个结构至少对我
来说，是组织笔记和想法的最好呈现。这个结构的总览是由折叠来完成的，例如隐藏文件的
大部分内容，只显示文件的概览及正在工作的部分。org通过一个单独的org折叠循环命令
来折叠显示的内容和隐藏功能，极大地简化了内容显示，这个循环功能绑定在了TAB键上。
** 标题
   标题定义了文件的大纲树。标题在org中以*号开头，在页面的边缘。举例来说，
  * 一级标题
  ** 二级标题
  *** 三级标题
      内容
  *** 三级标题
      其他内容
  * 另一个一级标题
这些定义在org-footnote-section中的名称是保留关键字。不要用它作为你的文件标题
一些人会觉得多个*号太碍眼，想要以空白符加上一个单一的星号来作为标题的开头，可以
查看15.9章【清爽视图】，236页。
一个子目录下的空行被认为是该子目录的一部分，它同样会被子目录折叠。但是，当你留下
至少两个空行时，在你折叠时会留下一个空行。这是你可以更好的组织折叠后的视图。
查看变量org-cycle-separator-lines，你也可以通过这个变量来调整它。
** 2.2可视化循环折叠
*** 2.2.1全局和局部循环折叠
    大纲化使得在编辑区部分隐藏文件内容成为可能。org中使用两个快捷键来完成编辑区
的可视化折叠循环，TAB和S-TAB。
TAB(org-cycle)
            子目录循环：折叠当前的目录
